MvcApplication1/MvcApplication1/Controllers/NewAsyncController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Linq;

namespace MvcApplication1.Controllers
{
    public class NewAsyncController : AsyncController
    {
        public async Task<ActionResult> Acao(int id = 2)
        {
            var cron = new Stopwatch();
            cron.Start();
            var svc = new TaskService.Service1Client();

            var results = await Task.WhenAll(from e in Enumerable.Range(0, 5) select svc.GetDataAsync(id + e));
            string transformedValue = string.Join(", ", results);
            
            var time = Convert.ToDouble(cron.ElapsedMilliseconds) / 1000;
            ViewBag.Time = time;
            return View("RetornoServico", (object)transformedValue);
        }
    }
}

MvcApplication1/MvcApplication1/Controllers/NotAsyncController.cs
using System;
using System.Diagnostics;
using System.Web.Mvc;

namespace MvcApplication1.Controllers
{
    public class NotAsyncController : Controller
    {
        public ActionResult Acao(int id = 3)
        {
            var cron = new Stopwatch();
            cron.Start();
            
            var svc = new TaskService.Service1Client();
            string transformedValue = "";
            for (int i = 0; i < 5; i++)
            {
                transformedValue += svc.GetData(id) + ", ";
                id++;
            }
            var time = Convert.ToDouble(cron.ElapsedMilliseconds) / 1000;
            
            ViewBag.Time = time;
            return View("RetornoServico", (object)transformedValue);
        }
    }
}

MvcApplication1/MvcApplication1/Controllers/OldAsyncController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Web.Mvc;

namespace MvcApplication1.Controllers
{
    public class OldAsyncController : AsyncController
    {
        Stopwatch cron;
        public void AcaoAsync(int id = 1)
        {
            cron = new Stopwatch();
            cron.Start();
            AsyncManager.OutstandingOperations.Increment(5);
            var svc = new AsyncOpService.Service1Client();
            AsyncManager.Parameters["transformedValue"] = "";
            svc.GetDataCompleted += (sender, args) =>
            {
                AsyncManager.Parameters["transformedValue"] = ((string)AsyncManager.Parameters["transformedValue"]) + args.Result + ", ";
                AsyncManager.OutstandingOperations.Decrement();
            };
            for (int i = 0; i < 5; i++)
            {
                svc.GetDataAsync(id);
                id++;
            }
        }
        public ActionResult AcaoCompleted(string transformedValue)
        {

            var time = Convert.ToDouble(cron.ElapsedMilliseconds) / 1000;
            ViewBag.Time = time;
            return View("RetornoServico", (object)transformedValue);
        }


    }
}

MvcApplication1/MvcApplication1/Views/Shared/RetornoServico.cshtml
@model string

<h1>@ViewContext.RouteData.Values["controller"]</h1>

<h2>E o valor eh "@Model"</h2>

Levou @ViewBag.Time segundos

MvcApplication1/MvcApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>TechEd 2011 - ASP.NET MVC 4 (Async)</title>
        <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
        <meta name="viewport" content="width=device-width">
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("Lambda3", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("NOT Async", "Acao", "NotAsync")</li>
                            <li>@Html.ActionLink("OLD Async", "Acao", "OldAsync")</li>
                            <li>@Html.ActionLink("NEW Async", "Acao", "NewAsync")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; 2011 - Lambda3</p>
                </div>
                <div class="float-right">
                    <ul id="social">
                        <li><a href="http://www.facebook.com/pages/Lambda3/211533205541864" class="facebook">Facebook</a></li>
                        <li><a href="http://twitter.com/lambdatres" class="twitter">Twitter</a></li>
                    </ul>
                </div>
            </div>
        </footer>
    </body>
</html>

MvcApplication1/MvcApplication1/Views/Shared/_LogOnPartial.cshtml
@if (Request.IsAuthenticated) {
    <p>
        Hello, @Html.ActionLink(User.Identity.Name, "ChangePassword", "Account", null, new { @class = "username" })!
        @Html.ActionLink("Log Off", "LogOff", "Account")
    </p>
} else {
    <ul>
        <li>@Html.ActionLink("Register", "Register", "Account", routeValues: null, htmlAttributes: new { id = "registerLink", data_dialog_title = "Registration" })</li>
        <li>@Html.ActionLink("Log on", "LogOn", "Account", routeValues: null, htmlAttributes: new { id = "logonLink", data_dialog_title = "Identification" })</li>
    </ul>
}